### ISSUE TITLE
Be nice if you could support subdomains

### ISSUE THREAD

**Issue by kaihendry** [buildo/terraform-aws-website#9]
E.g. foobar.example.com

It seems like you only support TLDs

**Comment by gabro** [comment]
@kaihendry yes, I agree it would be nice. It's unlikely we'll directly work on this since it's not a use-case for us, but I would welcome a PR adding support for it :)

**Comment by gabro** [comment]
Closing for now, but if anyone feels like to pick this up, I'll gladly review the work.
